### ISSUE TITLE
training slows down 

### ISSUE THREAD

**Issue by AntheaLi** [maciejzieba/HyperFlow#1]
Hello, authors of HyperFlow,

I recently saw your paper and was experimenting with your code. Training gets really slow after some time. I am training with 8 GPUs (batch size 128), and it slows down to around 30 sec per batch at epoch 250, which is 6-7 times slower than PointFlow. I kept the exact setting in this code release. I was wondering if there's something that I've done wrong. 

Thank you so much for the work.

**Comment by maciejmateuszzieba** [comment]
Hello,

Thank you for the comment. All of our experiments and comparison to PointFlow were made on a single GPU. For experiments reported in the paper, we used batch size equal to 50 what was sufficient to train the model in 4-6 days on a single GPU. The current implementation does not support multi GPU experiments in an effective way. We are going to solve this limitation in the nearest future.

**Comment by AntheaLi** [comment]
thanks for the help, really appreciate it.
